const PDFDocument = require('pdfkit');

// Renders the monthly summary JSON into a PDF stream and pipes it to `res`.
function renderSummaryPdf(res, summary) {
  const doc = new PDFDocument({ margin: 40, size: 'A4', layout: 'landscape' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="PULSE-Plus_Monthly_Summary_${summary.month}.pdf"`);
  doc.pipe(res);

  doc.fontSize(16).font('Helvetica-Bold').text('PULSE+ Monthly Summary Report', { align: 'center' });
  doc.fontSize(10).font('Helvetica').text('Population Update and Linking for Sustainable Empowerment', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(11).text(`Period: ${summary.month}`, { align: 'center' });
  doc.text('For submission to: Commission on Population and Development (POPCOM) Region 4A', { align: 'center' });
  doc.moveDown(1);

  doc.fontSize(12).font('Helvetica-Bold').text('RPFP Form 1 - Approved Participants by Municipality / Barangay');
  doc.moveDown(0.3);
  const rHeaders = ['Municipality', 'Barangay', 'Total', 'Male', 'Female', 'New Modern FP Users', 'Traditional FP Users'];
  const rWidths = [110, 130, 45, 45, 55, 130, 120];
  drawTableRow(doc, rHeaders, rWidths, true);
  summary.rpfpRows.forEach((row) => {
    drawTableRow(doc, [row.municipality, row.barangay, row.total, row.male, row.female, row.modernFpUsers, row.traditionalFpUsers], rWidths);
  });
  doc.moveDown(1);

  doc.fontSize(12).font('Helvetica-Bold').text('Documentation Reports - Approved Seminars/Activities');
  doc.moveDown(0.3);
  const dHeaders = ['Municipality', 'Barangay', 'Seminars Held', 'Target Participants', 'Actual Participants', 'Male', 'Female'];
  const dWidths = [110, 130, 90, 110, 110, 60, 60];
  drawTableRow(doc, dHeaders, dWidths, true);
  summary.docReportRows.forEach((row) => {
    drawTableRow(doc, [row.municipality, row.barangay, row.seminarsHeld, row.targetParticipants, row.actualParticipants, row.male, row.female], dWidths);
  });

  doc.moveDown(1.5);
  doc.fontSize(9).font('Helvetica-Oblique').text(`Generated by PULSE+ on ${new Date().toLocaleString()}. Auto-consolidated from approved records - no manual re-tallying performed.`);

  doc.end();
}

function drawTableRow(doc, cells, widths, isHeader = false) {
  const startX = doc.x;
  const startY = doc.y;
  doc.font(isHeader ? 'Helvetica-Bold' : 'Helvetica').fontSize(9);
  let x = startX;
  cells.forEach((cell, i) => {
    doc.text(String(cell), x, startY, { width: widths[i], continued: false });
    x += widths[i];
  });
  doc.moveDown(0.6);
  if (isHeader) {
    doc.moveTo(startX, doc.y - 2).lineTo(x, doc.y - 2).strokeColor('#999').stroke();
    doc.moveDown(0.2);
  }
}

module.exports = { renderSummaryPdf };
